#!/usr/bin/bash

function build_and_run(){
  cd PolyBench-NN
  make
  cp -r ./polybench ../out/rootfs_overlay/aarch64/lkmc/
  cd ..
  ./build --gem5-build-type fast --arch aarch64 gem5-buildroot
  ./run \
    --gem5-build-type fast \
    --arch aarch64 \
    --cpus 8 \
    --emulator gem5 \
    --eval-after 'm5 checkpoint;'
    -- \
    --cpu-type DerivO3CPU \
    --mem-type SimpleMemory \
    --caches \
    --l1d_size=128kB \
    --l1i_size=128kB \
    --l2cache \
    --l2_size=1024kB \
}


function restore_from_checkpoint(){
  ./run --gem5-build-type fast \
    --arch aarch64 \
    --cpus 8 \
    --emulator gem5 \
    --gem5-restore 1 \
    -- \
    --cpu-type DerivO3CPU \
    --mem-type SimpleMemory \
    --caches \
    --l1d_size=128kB \
    --l1i_size=128kB \
    --l2cache \
    --l2_size=1024kB \
}



while :; do
  case $1 in
    --run)
      build_and_run
      ;;
    --rerun)
      restore_from_checkpoint
      ;;
    --)
      shift
      break
      ;;
    -?*)
      printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
      ;;
    *)
      break
  esac

  shift
done
